DROP VIEW IF EXISTS public.v_service_report_with_flight;

CREATE VIEW public.v_service_report_with_flight AS
SELECT
  s.id,
  s.operator,
  s.handling_type,
  fs.flight_no            AS flight_no,
  fs.authority            AS station,
  fs.aircraft_type        AS aircraft_type,
  fs.registration         AS registration,
  fs.route                AS route,
  s.mtow,
  s.arrival_date,
  s.departure_date,
  s.day_night,
  s.sta,
  s.std,
  s.td,
  s.co,
  s.ob,
  s."to",
  s.ground_time,
  s.pax_in_adult_i,
  s.pax_in_inf_i,
  s.pax_in_adult_d,
  s.pax_in_inf_d,
  s.pax_transit,
  s.project_tags,
  s.check_in_system,
  s.performed_by,
  s.civil_aviation_fee,
  s.handling_fee,
  s.airport_charge,
  s.total_cost,
  s.currency,
  s.created_at,
  s.updated_at,
  s.review_status,
  s.review_comment,
  s.reviewed_by,
  s.reviewed_at,
  s.foreign_pax_in,
  s.foreign_pax_out,
  s.egyptian_pax_in,
  s.egyptian_pax_out,
  s.infant_in,
  s.infant_out,
  s.crew_count,
  s.total_departing_pax,
  s.estimated_foreign_bill,
  s.estimated_local_bill,
  s.fire_cart_qty,
  s.follow_me_qty,
  s.jetway_qty,
  s.met_folder_qty,
  s.file_flt_plan_qty,
  s.print_ops_flt_plan_qty,
  s.ata,
  s.atd,
  s.confirmation_no,
  s.flight_status,
  s.parking_day_hours,
  s.parking_night_hours,
  s.total_parking_hours,
  s.housing_days,
  s.landing_charge,
  s.parking_charge,
  s.housing_charge,
  s.fuel_charge,
  s.catering_charge,
  s.hotac_charge,
  s.flight_schedule_id,
  fs.id              AS fs_id,
  fs.flight_no       AS fs_flight_no,
  fs.registration    AS fs_registration,
  fs.aircraft_type   AS fs_aircraft_type,
  fs.route           AS fs_route,
  fs.sta             AS fs_sta,
  fs.std             AS fs_std,
  fs.skd_type        AS fs_skd_type,
  fs.clearance_type  AS fs_clearance_type,
  fs.arrival_date    AS fs_arrival_date,
  fs.departure_date  AS fs_departure_date,
  fs.authority       AS fs_authority,
  fs.airline_id      AS fs_airline_id,
  fs.status          AS fs_status
FROM public.service_reports s
LEFT JOIN public.flight_schedules fs ON fs.id = s.flight_schedule_id;

GRANT SELECT ON public.v_service_report_with_flight TO authenticated;
GRANT SELECT ON public.v_service_report_with_flight TO service_role;